# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_VBS) += vbs.o
vbs-y := core.o probe.o

obj-$(CONFIG_VBS_KVM_PLANES)	+= kvm_planes.o
obj-$(CONFIG_VBS_SEV_SNP)	+= sev_snp.o
obj-$(CONFIG_VBS_TDX)		+= tdx.o
obj-$(CONFIG_VBS_HV_VSM)	+= hv_vsm.o
obj-$(CONFIG_VBS_ARM_CCA)	+= arm_cca.o
